### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by ClauFischer** [alan-turing-institute/turing-commons#1]
Research a way to add citations to MKdocs.

**Comment by chrisdburr** [comment]
Will implement this plugin for bibtex functionality: https://pypi.org/project/mkdocs-bibtex/

**Comment by chrisdburr** [comment]
Implemented and tested on local machine. Working as expected.

**Comment by chrisdburr** [comment]
Added `mkdocs-bibtek` package requirement to `requirements.txt` to ensure netlify compiles citations correctly. 

Tested on live deployment and is working correctly. 

Closing issue, but will need to add pandoc style citations to all pages now.
